# Exercise 2.1: User Input and Data Types

#my way of taking input from user and storing in dictionary. This code is less robust as it does not handle invalid input and may crash if the user enters non-integer or non-float values for age and height, respectively. It also does not use functions to organize the code, which can make it harder to read and maintain.
age = int(input("How old are you? "))
height = float(input("What is your height? "))
favorite_color = input("What is your favorite color? ")

user_data = {
    "Age": age,
    "Height": height,
    "Favorite Color": favorite_color,
}
for key, value in user_data.items():
    print(f"{key}: {value} | Type: {type(value)}")


#Better way of taking input from user and storing in dictionary using functions generated by Copilot
# %%
#this code is more robust as it handles invalid input and prompts the user to enter valid input until they do so by using try-except blocks and while loops. 
def get_int(prompt):
    while True:
        val = input(prompt)
        try:
            return int(val)
        except ValueError:
            print("Please enter a valid integer (e.g., 25).")


def get_float(prompt):
    while True:
        val = input(prompt)
        try:
            return float(val)
        except ValueError:
            print("Please enter a valid number (e.g., 5.9).")

# It also uses a main function to organize the code and makes it easier to read and maintain.
def main():
    age = get_int("Enter your age: ")
    height = get_float("Enter your height (e.g., 5.9): ")
    favorite_color = input("Enter your favorite color: ").strip()

    user_data = {
        "Age": age,
        "Height": height,
        "Favorite Color": favorite_color,
    }

    print()
    for key, value in user_data.items():
        print(f"{key}: {value} | Type: {type(value)}")

# The if __name__ == "__main__": block ensures that the main function is only executed when the script is run directly, and not when it is imported as a module in another script. This is a common practice in Python to allow for better code organization and reusability.
if __name__ == "__main__":
    main()
