# .ini file is a configuration file that stores setting, not code.
# Allows configuration to be separated from code.

[API]
library_endpoint = http://216.10.245.166
github_endpoint = https://api.github.com/user