# .ini file is a configuration file that stores setting, not code.
# Allows configuration to be separated from code.

[API]
library_endpoint = http://216.10.245.166
github_endpoint = https://api.github.com
rsa_endpoint = http://rahulshettyacademy.com
httpbin_endpoint = https://httpbin.org
swagger_petstore_endpoint = https://petstore.swagger.io/v2